.TH "INSTALL Directory Reference" 3 "Sat Nov 16 2013" "Version 3.4.2" "LAPACK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
INSTALL Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBdlamch\&.f\fP"
.br
.ti -1c
.RI "file \fBdlamchf77\&.f\fP"
.br
.ti -1c
.RI "file \fBdlamchtst\&.f\fP"
.br
.ti -1c
.RI "file \fBdsecnd_EXT_ETIME\&.f\fP"
.br
.ti -1c
.RI "file \fBdsecnd_EXT_ETIME_\&.f\fP"
.br
.ti -1c
.RI "file \fBdsecnd_INT_CPU_TIME\&.f\fP"
.br
.ti -1c
.RI "file \fBdsecnd_INT_ETIME\&.f\fP"
.br
.ti -1c
.RI "file \fBdsecnd_NONE\&.f\fP"
.br
.ti -1c
.RI "file \fBdsecndtst\&.f\fP"
.br
.ti -1c
.RI "file \fBINSTALL/ilaver\&.f\fP"
.br
.ti -1c
.RI "file \fBLAPACK_version\&.f\fP"
.br
.ti -1c
.RI "file \fBINSTALL/lsame\&.f\fP"
.br
.ti -1c
.RI "file \fBlsametst\&.f\fP"
.br
.ti -1c
.RI "file \fBsecond_EXT_ETIME\&.f\fP"
.br
.ti -1c
.RI "file \fBsecond_EXT_ETIME_\&.f\fP"
.br
.ti -1c
.RI "file \fBsecond_INT_CPU_TIME\&.f\fP"
.br
.ti -1c
.RI "file \fBsecond_INT_ETIME\&.f\fP"
.br
.ti -1c
.RI "file \fBsecond_NONE\&.f\fP"
.br
.ti -1c
.RI "file \fBsecondtst\&.f\fP"
.br
.ti -1c
.RI "file \fBslamch\&.f\fP"
.br
.ti -1c
.RI "file \fBslamchf77\&.f\fP"
.br
.ti -1c
.RI "file \fBslamchtst\&.f\fP"
.br
.ti -1c
.RI "file \fBtstiee\&.f\fP"
.br
.in -1c
