.TH "xerbla.f" 3 "Sat Nov 16 2013" "Version 3.4.2" "LAPACK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
xerbla.f \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "subroutine \fBxerbla\fP (SRNAME, INFO)"
.br
.RI "\fI\fBXERBLA\fP \fP"
.in -1c
.SH "Function/Subroutine Documentation"
.PP 
.SS "subroutine xerbla (character*(*)SRNAME, integerINFO)"

.PP
\fBXERBLA\fP \fBPurpose: \fP
.RS 4

.PP
.nf
 XERBLA  is an error handler for the LAPACK routines.
 It is called by an LAPACK routine if an input parameter has an
 invalid value.  A message is printed and execution stops.

 Installers may consider modifying the STOP statement in order to
 call system-specific exception-handling facilities.
.fi
.PP
 
.RE
.PP
\fBParameters:\fP
.RS 4
\fISRNAME\fP 
.PP
.nf
          SRNAME is CHARACTER*(*)
          The name of the routine which called XERBLA.
.fi
.PP
.br
\fIINFO\fP 
.PP
.nf
          INFO is INTEGER
          The position of the invalid parameter in the parameter list
          of the calling routine.
.fi
.PP
 
.RE
.PP
\fBAuthor:\fP
.RS 4
Univ\&. of Tennessee 
.PP
Univ\&. of California Berkeley 
.PP
Univ\&. of Colorado Denver 
.PP
NAG Ltd\&. 
.RE
.PP
\fBDate:\fP
.RS 4
November 2011 
.RE
.PP

.PP
Definition at line 61 of file BLAS/SRC/xerbla\&.f\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for LAPACK from the source code\&.
