.TH "chla_transtype.f" 3 "Sat Nov 16 2013" "Version 3.4.2" "LAPACK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
chla_transtype.f \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "CHARACTER *1 function \fBchla_transtype\fP (TRANS)"
.br
.RI "\fI\fBCHLA_TRANSTYPE\fP \fP"
.in -1c
.SH "Function/Subroutine Documentation"
.PP 
.SS "CHARACTER*1 function chla_transtype (integerTRANS)"

.PP
\fBCHLA_TRANSTYPE\fP  
.PP
\fBPurpose: \fP
.RS 4

.PP
.nf
 This subroutine translates from a BLAST-specified integer constant to
 the character string specifying a transposition operation.

 CHLA_TRANSTYPE returns an CHARACTER*1.  If CHLA_TRANSTYPE is 'X',
 then input is not an integer indicating a transposition operator.
 Otherwise CHLA_TRANSTYPE returns the constant value corresponding to
 TRANS.
.fi
.PP
 
.RE
.PP
\fBAuthor:\fP
.RS 4
Univ\&. of Tennessee 
.PP
Univ\&. of California Berkeley 
.PP
Univ\&. of Colorado Denver 
.PP
NAG Ltd\&. 
.RE
.PP
\fBDate:\fP
.RS 4
November 2011 
.RE
.PP

.PP
Definition at line 59 of file chla_transtype\&.f\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for LAPACK from the source code\&.
