.TH "classq.f" 3 "Sat Nov 16 2013" "Version 3.4.2" "LAPACK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
classq.f \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "subroutine \fBclassq\fP (N, X, INCX, SCALE, SUMSQ)"
.br
.RI "\fI\fBCLASSQ\fP updates a sum of squares represented in scaled form\&. \fP"
.in -1c
.SH "Function/Subroutine Documentation"
.PP 
.SS "subroutine classq (integerN, complex, dimension( * )X, integerINCX, realSCALE, realSUMSQ)"

.PP
\fBCLASSQ\fP updates a sum of squares represented in scaled form\&.  
.PP
\fBPurpose: \fP
.RS 4

.PP
.nf
 CLASSQ returns the values scl and ssq such that

    ( scl**2 )*ssq = x( 1 )**2 +...+ x( n )**2 + ( scale**2 )*sumsq,

 where x( i ) = abs( X( 1 + ( i - 1 )*INCX ) ). The value of sumsq is
 assumed to be at least unity and the value of ssq will then satisfy

    1.0 .le. ssq .le. ( sumsq + 2*n ).

 scale is assumed to be non-negative and scl returns the value

    scl = max( scale, abs( real( x( i ) ) ), abs( aimag( x( i ) ) ) ),
           i

 scale and sumsq must be supplied in SCALE and SUMSQ respectively.
 SCALE and SUMSQ are overwritten by scl and ssq respectively.

 The routine makes only one pass through the vector X.
.fi
.PP
 
.RE
.PP
\fBParameters:\fP
.RS 4
\fIN\fP 
.PP
.nf
          N is INTEGER
          The number of elements to be used from the vector X.
.fi
.PP
.br
\fIX\fP 
.PP
.nf
          X is COMPLEX array, dimension (N)
          The vector x as described above.
             x( i )  = X( 1 + ( i - 1 )*INCX ), 1 <= i <= n.
.fi
.PP
.br
\fIINCX\fP 
.PP
.nf
          INCX is INTEGER
          The increment between successive values of the vector X.
          INCX > 0.
.fi
.PP
.br
\fISCALE\fP 
.PP
.nf
          SCALE is REAL
          On entry, the value  scale  in the equation above.
          On exit, SCALE is overwritten with the value  scl .
.fi
.PP
.br
\fISUMSQ\fP 
.PP
.nf
          SUMSQ is REAL
          On entry, the value  sumsq  in the equation above.
          On exit, SUMSQ is overwritten with the value  ssq .
.fi
.PP
 
.RE
.PP
\fBAuthor:\fP
.RS 4
Univ\&. of Tennessee 
.PP
Univ\&. of California Berkeley 
.PP
Univ\&. of Colorado Denver 
.PP
NAG Ltd\&. 
.RE
.PP
\fBDate:\fP
.RS 4
September 2012 
.RE
.PP

.PP
Definition at line 107 of file classq\&.f\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for LAPACK from the source code\&.
