.TH "dasum.f" 3 "Sat Nov 16 2013" "Version 3.4.2" "LAPACK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
dasum.f \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "DOUBLE PRECISION function \fBdasum\fP (N, DX, INCX)"
.br
.RI "\fI\fBDASUM\fP \fP"
.in -1c
.SH "Function/Subroutine Documentation"
.PP 
.SS "DOUBLE PRECISION function dasum (integerN, double precision, dimension(*)DX, integerINCX)"

.PP
\fBDASUM\fP \fBPurpose: \fP
.RS 4

.PP
.nf
    DASUM takes the sum of the absolute values.
.fi
.PP
 
.RE
.PP
\fBAuthor:\fP
.RS 4
Univ\&. of Tennessee 
.PP
Univ\&. of California Berkeley 
.PP
Univ\&. of Colorado Denver 
.PP
NAG Ltd\&. 
.RE
.PP
\fBDate:\fP
.RS 4
November 2011 
.RE
.PP
\fBFurther Details: \fP
.RS 4

.PP
.nf
     jack dongarra, linpack, 3/11/78.
     modified 3/93 to return if incx .le. 0.
     modified 12/3/93, array(1) declarations changed to array(*)
.fi
.PP
 
.RE
.PP

.PP
Definition at line 52 of file dasum\&.f\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for LAPACK from the source code\&.
