.TH "disnan.f" 3 "Sat Nov 16 2013" "Version 3.4.2" "LAPACK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
disnan.f \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "LOGICAL function \fBdisnan\fP (DIN)"
.br
.RI "\fI\fBDISNAN\fP tests input for NaN\&. \fP"
.in -1c
.SH "Function/Subroutine Documentation"
.PP 
.SS "LOGICAL function disnan (double precisionDIN)"

.PP
\fBDISNAN\fP tests input for NaN\&.  
.PP
\fBPurpose: \fP
.RS 4

.PP
.nf
 DISNAN returns .TRUE. if its argument is NaN, and .FALSE.
 otherwise.  To be replaced by the Fortran 2003 intrinsic in the
 future.
.fi
.PP
 
.RE
.PP
\fBParameters:\fP
.RS 4
\fIDIN\fP 
.PP
.nf
          DIN is DOUBLE PRECISION
          Input to test for NaN.
.fi
.PP
 
.RE
.PP
\fBAuthor:\fP
.RS 4
Univ\&. of Tennessee 
.PP
Univ\&. of California Berkeley 
.PP
Univ\&. of Colorado Denver 
.PP
NAG Ltd\&. 
.RE
.PP
\fBDate:\fP
.RS 4
September 2012 
.RE
.PP

.PP
Definition at line 60 of file disnan\&.f\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for LAPACK from the source code\&.
