.TH "dlamrg.f" 3 "Sat Nov 16 2013" "Version 3.4.2" "LAPACK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
dlamrg.f \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "subroutine \fBdlamrg\fP (N1, N2, A, DTRD1, DTRD2, INDEX)"
.br
.RI "\fI\fBDLAMRG\fP creates a permutation list to merge the entries of two independently sorted sets into a single set sorted in ascending order\&. \fP"
.in -1c
.SH "Function/Subroutine Documentation"
.PP 
.SS "subroutine dlamrg (integerN1, integerN2, double precision, dimension( * )A, integerDTRD1, integerDTRD2, integer, dimension( * )INDEX)"

.PP
\fBDLAMRG\fP creates a permutation list to merge the entries of two independently sorted sets into a single set sorted in ascending order\&.  
.PP
\fBPurpose: \fP
.RS 4

.PP
.nf
 DLAMRG will create a permutation list which will merge the elements
 of A (which is composed of two independently sorted sets) into a
 single set which is sorted in ascending order.
.fi
.PP
 
.RE
.PP
\fBParameters:\fP
.RS 4
\fIN1\fP 
.PP
.nf
          N1 is INTEGER
.fi
.PP
.br
\fIN2\fP 
.PP
.nf
          N2 is INTEGER
         These arguements contain the respective lengths of the two
         sorted lists to be merged.
.fi
.PP
.br
\fIA\fP 
.PP
.nf
          A is DOUBLE PRECISION array, dimension (N1+N2)
         The first N1 elements of A contain a list of numbers which
         are sorted in either ascending or descending order.  Likewise
         for the final N2 elements.
.fi
.PP
.br
\fIDTRD1\fP 
.PP
.nf
          DTRD1 is INTEGER
.fi
.PP
.br
\fIDTRD2\fP 
.PP
.nf
          DTRD2 is INTEGER
         These are the strides to be taken through the array A.
         Allowable strides are 1 and -1.  They indicate whether a
         subset of A is sorted in ascending (DTRDx = 1) or descending
         (DTRDx = -1) order.
.fi
.PP
.br
\fIINDEX\fP 
.PP
.nf
          INDEX is INTEGER array, dimension (N1+N2)
         On exit this array will contain a permutation such that
         if B( I ) = A( INDEX( I ) ) for I=1,N1+N2, then B will be
         sorted in ascending order.
.fi
.PP
 
.RE
.PP
\fBAuthor:\fP
.RS 4
Univ\&. of Tennessee 
.PP
Univ\&. of California Berkeley 
.PP
Univ\&. of Colorado Denver 
.PP
NAG Ltd\&. 
.RE
.PP
\fBDate:\fP
.RS 4
September 2012 
.RE
.PP

.PP
Definition at line 100 of file dlamrg\&.f\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for LAPACK from the source code\&.
