.TH "dlapy3.f" 3 "Sat Nov 16 2013" "Version 3.4.2" "LAPACK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
dlapy3.f \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "DOUBLE PRECISION function \fBdlapy3\fP (X, Y, Z)"
.br
.RI "\fI\fBDLAPY3\fP returns sqrt(x2+y2+z2)\&. \fP"
.in -1c
.SH "Function/Subroutine Documentation"
.PP 
.SS "DOUBLE PRECISION function dlapy3 (double precisionX, double precisionY, double precisionZ)"

.PP
\fBDLAPY3\fP returns sqrt(x2+y2+z2)\&.  
.PP
\fBPurpose: \fP
.RS 4

.PP
.nf
 DLAPY3 returns sqrt(x**2+y**2+z**2), taking care not to cause
 unnecessary overflow.
.fi
.PP
 
.RE
.PP
\fBParameters:\fP
.RS 4
\fIX\fP 
.PP
.nf
          X is DOUBLE PRECISION
.fi
.PP
.br
\fIY\fP 
.PP
.nf
          Y is DOUBLE PRECISION
.fi
.PP
.br
\fIZ\fP 
.PP
.nf
          Z is DOUBLE PRECISION
          X, Y and Z specify the values x, y and z.
.fi
.PP
 
.RE
.PP
\fBAuthor:\fP
.RS 4
Univ\&. of Tennessee 
.PP
Univ\&. of California Berkeley 
.PP
Univ\&. of Colorado Denver 
.PP
NAG Ltd\&. 
.RE
.PP
\fBDate:\fP
.RS 4
September 2012 
.RE
.PP

.PP
Definition at line 69 of file dlapy3\&.f\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for LAPACK from the source code\&.
