.TH "dlaqr1.f" 3 "Sat Nov 16 2013" "Version 3.4.2" "LAPACK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
dlaqr1.f \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "subroutine \fBdlaqr1\fP (N, H, LDH, SR1, SI1, SR2, SI2, V)"
.br
.RI "\fI\fBDLAQR1\fP sets a scalar multiple of the first column of the product of 2-by-2 or 3-by-3 matrix H and specified shifts\&. \fP"
.in -1c
.SH "Function/Subroutine Documentation"
.PP 
.SS "subroutine dlaqr1 (integerN, double precision, dimension( ldh, * )H, integerLDH, double precisionSR1, double precisionSI1, double precisionSR2, double precisionSI2, double precision, dimension( * )V)"

.PP
\fBDLAQR1\fP sets a scalar multiple of the first column of the product of 2-by-2 or 3-by-3 matrix H and specified shifts\&.  
.PP
\fBPurpose: \fP
.RS 4

.PP
.nf
      Given a 2-by-2 or 3-by-3 matrix H, DLAQR1 sets v to a
      scalar multiple of the first column of the product

      (*)  K = (H - (sr1 + i*si1)*I)*(H - (sr2 + i*si2)*I)

      scaling to avoid overflows and most underflows. It
      is assumed that either

              1) sr1 = sr2 and si1 = -si2
          or
              2) si1 = si2 = 0.

      This is useful for starting double implicit shift bulges
      in the QR algorithm.
.fi
.PP
 
.RE
.PP
\fBParameters:\fP
.RS 4
\fIN\fP 
.PP
.nf
          N is integer
              Order of the matrix H. N must be either 2 or 3.
.fi
.PP
.br
\fIH\fP 
.PP
.nf
          H is DOUBLE PRECISION array of dimension (LDH,N)
              The 2-by-2 or 3-by-3 matrix H in (*).
.fi
.PP
.br
\fILDH\fP 
.PP
.nf
          LDH is integer
              The leading dimension of H as declared in
              the calling procedure.  LDH.GE.N
.fi
.PP
.br
\fISR1\fP 
.PP
.nf
          SR1 is DOUBLE PRECISION
.fi
.PP
.br
\fISI1\fP 
.PP
.nf
          SI1 is DOUBLE PRECISION
.fi
.PP
.br
\fISR2\fP 
.PP
.nf
          SR2 is DOUBLE PRECISION
.fi
.PP
.br
\fISI2\fP 
.PP
.nf
          SI2 is DOUBLE PRECISION
              The shifts in (*).
.fi
.PP
.br
\fIV\fP 
.PP
.nf
          V is DOUBLE PRECISION array of dimension N
              A scalar multiple of the first column of the
              matrix K in (*).
.fi
.PP
 
.RE
.PP
\fBAuthor:\fP
.RS 4
Univ\&. of Tennessee 
.PP
Univ\&. of California Berkeley 
.PP
Univ\&. of Colorado Denver 
.PP
NAG Ltd\&. 
.RE
.PP
\fBDate:\fP
.RS 4
September 2012 
.RE
.PP
\fBContributors: \fP
.RS 4
Karen Braman and Ralph Byers, Department of Mathematics, University of Kansas, USA 
.RE
.PP

.PP
Definition at line 122 of file dlaqr1\&.f\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for LAPACK from the source code\&.
