.TH "dlartg.f" 3 "Sat Nov 16 2013" "Version 3.4.2" "LAPACK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
dlartg.f \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "subroutine \fBdlartg\fP (F, G, CS, SN, R)"
.br
.RI "\fI\fBDLARTG\fP generates a plane rotation with real cosine and real sine\&. \fP"
.in -1c
.SH "Function/Subroutine Documentation"
.PP 
.SS "subroutine dlartg (double precisionF, double precisionG, double precisionCS, double precisionSN, double precisionR)"

.PP
\fBDLARTG\fP generates a plane rotation with real cosine and real sine\&.  
.PP
\fBPurpose: \fP
.RS 4

.PP
.nf
 DLARTG generate a plane rotation so that

    [  CS  SN  ]  .  [ F ]  =  [ R ]   where CS**2 + SN**2 = 1.
    [ -SN  CS  ]     [ G ]     [ 0 ]

 This is a slower, more accurate version of the BLAS1 routine DROTG,
 with the following other differences:
    F and G are unchanged on return.
    If G=0, then CS=1 and SN=0.
    If F=0 and (G .ne. 0), then CS=0 and SN=1 without doing any
       floating point operations (saves work in DBDSQR when
       there are zeros on the diagonal).

 If F exceeds G in magnitude, CS will be positive.
.fi
.PP
 
.RE
.PP
\fBParameters:\fP
.RS 4
\fIF\fP 
.PP
.nf
          F is DOUBLE PRECISION
          The first component of vector to be rotated.
.fi
.PP
.br
\fIG\fP 
.PP
.nf
          G is DOUBLE PRECISION
          The second component of vector to be rotated.
.fi
.PP
.br
\fICS\fP 
.PP
.nf
          CS is DOUBLE PRECISION
          The cosine of the rotation.
.fi
.PP
.br
\fISN\fP 
.PP
.nf
          SN is DOUBLE PRECISION
          The sine of the rotation.
.fi
.PP
.br
\fIR\fP 
.PP
.nf
          R is DOUBLE PRECISION
          The nonzero component of the rotated vector.

  This version has a few statements commented out for thread safety
  (machine parameters are computed on each entry). 10 feb 03, SJH.
.fi
.PP
 
.RE
.PP
\fBAuthor:\fP
.RS 4
Univ\&. of Tennessee 
.PP
Univ\&. of California Berkeley 
.PP
Univ\&. of Colorado Denver 
.PP
NAG Ltd\&. 
.RE
.PP
\fBDate:\fP
.RS 4
September 2012 
.RE
.PP

.PP
Definition at line 98 of file dlartg\&.f\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for LAPACK from the source code\&.
