.TH "dnrm2.f" 3 "Sat Nov 16 2013" "Version 3.4.2" "LAPACK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
dnrm2.f \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "DOUBLE PRECISION function \fBdnrm2\fP (N, X, INCX)"
.br
.RI "\fI\fBDNRM2\fP \fP"
.in -1c
.SH "Function/Subroutine Documentation"
.PP 
.SS "DOUBLE PRECISION function dnrm2 (integerN, double precision, dimension(*)X, integerINCX)"

.PP
\fBDNRM2\fP \fBPurpose: \fP
.RS 4

.PP
.nf
 DNRM2 returns the euclidean norm of a vector via the function
 name, so that

    DNRM2 := sqrt( x'*x )
.fi
.PP
 
.RE
.PP
\fBAuthor:\fP
.RS 4
Univ\&. of Tennessee 
.PP
Univ\&. of California Berkeley 
.PP
Univ\&. of Colorado Denver 
.PP
NAG Ltd\&. 
.RE
.PP
\fBDate:\fP
.RS 4
November 2011 
.RE
.PP
\fBFurther Details: \fP
.RS 4

.PP
.nf
  -- This version written on 25-October-1982.
     Modified on 14-October-1993 to inline the call to DLASSQ.
     Sven Hammarling, Nag Ltd.
.fi
.PP
 
.RE
.PP

.PP
Definition at line 55 of file dnrm2\&.f\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for LAPACK from the source code\&.
