.TH "drotm.f" 3 "Sat Nov 16 2013" "Version 3.4.2" "LAPACK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
drotm.f \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "subroutine \fBdrotm\fP (N, DX, INCX, DY, INCY, DPARAM)"
.br
.RI "\fI\fBDROTM\fP \fP"
.in -1c
.SH "Function/Subroutine Documentation"
.PP 
.SS "subroutine drotm (integerN, double precision, dimension(*)DX, integerINCX, double precision, dimension(*)DY, integerINCY, double precision, dimension(5)DPARAM)"

.PP
\fBDROTM\fP \fBPurpose: \fP
.RS 4

.PP
.nf
    APPLY THE MODIFIED GIVENS TRANSFORMATION, H, TO THE 2 BY N MATRIX

    (DX**T) , WHERE **T INDICATES TRANSPOSE. THE ELEMENTS OF DX ARE IN
    (DY**T)

    DX(LX+I*INCX), I = 0 TO N-1, WHERE LX = 1 IF INCX .GE. 0, ELSE
    LX = (-INCX)*N, AND SIMILARLY FOR SY USING LY AND INCY.
    WITH DPARAM(1)=DFLAG, H HAS ONE OF THE FOLLOWING FORMS..

    DFLAG=-1.D0     DFLAG=0.D0        DFLAG=1.D0     DFLAG=-2.D0

      (DH11  DH12)    (1.D0  DH12)    (DH11  1.D0)    (1.D0  0.D0)
    H=(          )    (          )    (          )    (          )
      (DH21  DH22),   (DH21  1.D0),   (-1.D0 DH22),   (0.D0  1.D0).
    SEE DROTMG FOR A DESCRIPTION OF DATA STORAGE IN DPARAM.
.fi
.PP
 
.RE
.PP
\fBParameters:\fP
.RS 4
\fIN\fP 
.PP
.nf
          N is INTEGER
         number of elements in input vector(s)
.fi
.PP
.br
\fIDX\fP 
.PP
.nf
          DX is DOUBLE PRECISION array, dimension N
         double precision vector with N elements
.fi
.PP
.br
\fIINCX\fP 
.PP
.nf
          INCX is INTEGER
         storage spacing between elements of DX
.fi
.PP
.br
\fIDY\fP 
.PP
.nf
          DY is DOUBLE PRECISION array, dimension N
         double precision vector with N elements
.fi
.PP
.br
\fIINCY\fP 
.PP
.nf
          INCY is INTEGER
         storage spacing between elements of DY
.fi
.PP
.br
\fIDPARAM\fP 
.PP
.nf
          DPARAM is DOUBLE PRECISION array, dimension 5
     DPARAM(1)=DFLAG
     DPARAM(2)=DH11
     DPARAM(3)=DH21
     DPARAM(4)=DH12
     DPARAM(5)=DH22
.fi
.PP
 
.RE
.PP
\fBAuthor:\fP
.RS 4
Univ\&. of Tennessee 
.PP
Univ\&. of California Berkeley 
.PP
Univ\&. of Colorado Denver 
.PP
NAG Ltd\&. 
.RE
.PP
\fBDate:\fP
.RS 4
November 2011 
.RE
.PP

.PP
Definition at line 99 of file drotm\&.f\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for LAPACK from the source code\&.
