.TH "dsdot.f" 3 "Sat Nov 16 2013" "Version 3.4.2" "LAPACK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
dsdot.f \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "DOUBLE PRECISION function \fBdsdot\fP (N, SX, INCX, SY, INCY)"
.br
.RI "\fI\fBDSDOT\fP \fP"
.in -1c
.SH "Function/Subroutine Documentation"
.PP 
.SS "DOUBLE PRECISION function dsdot (integerN, real, dimension(*)SX, integerINCX, real, dimension(*)SY, integerINCY)"

.PP
\fBDSDOT\fP \fBPurpose: \fP
.RS 4

.PP
.nf
 Compute the inner product of two vectors with extended
 precision accumulation and result.

 Returns D.P. dot product accumulated in D.P., for S.P. SX and SY
 DSDOT = sum for I = 0 to N-1 of  SX(LX+I*INCX) * SY(LY+I*INCY),
 where LX = 1 if INCX .GE. 0, else LX = 1+(1-N)*INCX, and LY is
 defined in a similar way using INCY.
.fi
.PP
 
.RE
.PP
\fBParameters:\fP
.RS 4
\fIN\fP 
.PP
.nf
          N is INTEGER
         number of elements in input vector(s)
.fi
.PP
.br
\fISX\fP 
.PP
.nf
          SX is REAL array, dimension(N)
         single precision vector with N elements
.fi
.PP
.br
\fIINCX\fP 
.PP
.nf
          INCX is INTEGER
          storage spacing between elements of SX
.fi
.PP
.br
\fISY\fP 
.PP
.nf
          SY is REAL array, dimension(N)
         single precision vector with N elements
.fi
.PP
.br
\fIINCY\fP 
.PP
.nf
          INCY is INTEGER
         storage spacing between elements of SY
.fi
.PP
.RE
.PP
\fBReturns:\fP
.RS 4
DSDOT 
.PP
.nf
          DSDOT is DOUBLE PRECISION
         DSDOT  double precision dot product (zero if N.LE.0)
.fi
.PP
 
.RE
.PP
\fBAuthor:\fP
.RS 4
Univ\&. of Tennessee 
.PP
Univ\&. of California Berkeley 
.PP
Univ\&. of Colorado Denver 
.PP
NAG Ltd\&. 
.RE
.PP
\fBDate:\fP
.RS 4
November 2011 
.RE
.PP
\fBFurther Details: \fP
.RS 4

.PP
.nf
 
.fi
.PP
 
.RE
.PP
\fBReferences: \fP
.RS 4

.PP
.nf
  C. L. Lawson, R. J. Hanson, D. R. Kincaid and F. T.
  Krogh, Basic linear algebra subprograms for Fortran
  usage, Algorithm No. 539, Transactions on Mathematical
  Software 5, 3 (September 1979), pp. 308-323.

  REVISION HISTORY  (YYMMDD)

  791001  DATE WRITTEN
  890831  Modified array declarations.  (WRB)
  890831  REVISION DATE from Version 3.2
  891214  Prologue converted to Version 4.0 format.  (BAB)
  920310  Corrected definition of LX in DESCRIPTION.  (WRB)
  920501  Reformatted the REFERENCES section.  (WRB)
  070118  Reformat to LAPACK style (JL)
.fi
.PP
 
.RE
.PP

.PP
Definition at line 120 of file dsdot\&.f\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for LAPACK from the source code\&.
