.TH "dsecnd_EXT_ETIME.f" 3 "Sat Nov 16 2013" "Version 3.4.2" "LAPACK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
dsecnd_EXT_ETIME.f \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "DOUBLE PRECISION function \fBdsecnd\fP ()"
.br
.RI "\fI\fBDSECND\fP Using ETIME \fP"
.in -1c
.SH "Function/Subroutine Documentation"
.PP 
.SS "DOUBLE PRECISION function dsecnd ()"

.PP
\fBDSECND\fP Using ETIME \fBPurpose: \fP
.RS 4

.PP
.nf
  DSECND returns the user time for a process in seconds.
  This version gets the time from the EXTERNAL system function ETIME.
.fi
.PP
 
.RE
.PP
\fBAuthor:\fP
.RS 4
Univ\&. of Tennessee 
.PP
Univ\&. of California Berkeley 
.PP
Univ\&. of Colorado Denver 
.PP
NAG Ltd\&. 
.RE
.PP
\fBDate:\fP
.RS 4
November 2011 
.RE
.PP

.PP
Definition at line 36 of file dsecnd_EXT_ETIME\&.f\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for LAPACK from the source code\&.
