.TH "ieeeck.f" 3 "Sat Nov 16 2013" "Version 3.4.2" "LAPACK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ieeeck.f \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "INTEGER function \fBieeeck\fP (ISPEC, ZERO, ONE)"
.br
.RI "\fI\fBIEEECK\fP \fP"
.in -1c
.SH "Function/Subroutine Documentation"
.PP 
.SS "INTEGER function ieeeck (integerISPEC, realZERO, realONE)"

.PP
\fBIEEECK\fP  
.PP
\fBPurpose: \fP
.RS 4

.PP
.nf
 IEEECK is called from the ILAENV to verify that Infinity and
 possibly NaN arithmetic is safe (i.e. will not trap).
.fi
.PP
 
.RE
.PP
\fBParameters:\fP
.RS 4
\fIISPEC\fP 
.PP
.nf
          ISPEC is INTEGER
          Specifies whether to test just for inifinity arithmetic
          or whether to test for infinity and NaN arithmetic.
          = 0: Verify infinity arithmetic only.
          = 1: Verify infinity and NaN arithmetic.
.fi
.PP
.br
\fIZERO\fP 
.PP
.nf
          ZERO is REAL
          Must contain the value 0.0
          This is passed to prevent the compiler from optimizing
          away this code.
.fi
.PP
.br
\fIONE\fP 
.PP
.nf
          ONE is REAL
          Must contain the value 1.0
          This is passed to prevent the compiler from optimizing
          away this code.

  RETURN VALUE:  INTEGER
          = 0:  Arithmetic failed to produce the correct answers
          = 1:  Arithmetic produced the correct answers
.fi
.PP
 
.RE
.PP
\fBAuthor:\fP
.RS 4
Univ\&. of Tennessee 
.PP
Univ\&. of California Berkeley 
.PP
Univ\&. of Colorado Denver 
.PP
NAG Ltd\&. 
.RE
.PP
\fBDate:\fP
.RS 4
November 2011 
.RE
.PP

.PP
Definition at line 83 of file ieeeck\&.f\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for LAPACK from the source code\&.
