.TH "ilaclc.f" 3 "Sat Nov 16 2013" "Version 3.4.2" "LAPACK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ilaclc.f \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "INTEGER function \fBilaclc\fP (M, N, A, LDA)"
.br
.RI "\fI\fBILACLC\fP scans a matrix for its last non-zero column\&. \fP"
.in -1c
.SH "Function/Subroutine Documentation"
.PP 
.SS "INTEGER function ilaclc (integerM, integerN, complex, dimension( lda, * )A, integerLDA)"

.PP
\fBILACLC\fP scans a matrix for its last non-zero column\&.  
.PP
\fBPurpose: \fP
.RS 4

.PP
.nf
 ILACLC scans A for its last non-zero column.
.fi
.PP
 
.RE
.PP
\fBParameters:\fP
.RS 4
\fIM\fP 
.PP
.nf
          M is INTEGER
          The number of rows of the matrix A.
.fi
.PP
.br
\fIN\fP 
.PP
.nf
          N is INTEGER
          The number of columns of the matrix A.
.fi
.PP
.br
\fIA\fP 
.PP
.nf
          A is COMPLEX array, dimension (LDA,N)
          The m by n matrix A.
.fi
.PP
.br
\fILDA\fP 
.PP
.nf
          LDA is INTEGER
          The leading dimension of the array A. LDA >= max(1,M).
.fi
.PP
 
.RE
.PP
\fBAuthor:\fP
.RS 4
Univ\&. of Tennessee 
.PP
Univ\&. of California Berkeley 
.PP
Univ\&. of Colorado Denver 
.PP
NAG Ltd\&. 
.RE
.PP
\fBDate:\fP
.RS 4
September 2012 
.RE
.PP

.PP
Definition at line 79 of file ilaclc\&.f\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for LAPACK from the source code\&.
