.TH "iladiag.f" 3 "Sat Nov 16 2013" "Version 3.4.2" "LAPACK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
iladiag.f \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "INTEGER function \fBiladiag\fP (DIAG)"
.br
.RI "\fI\fBILADIAG\fP \fP"
.in -1c
.SH "Function/Subroutine Documentation"
.PP 
.SS "INTEGER function iladiag (characterDIAG)"

.PP
\fBILADIAG\fP  
.PP
\fBPurpose: \fP
.RS 4

.PP
.nf
 This subroutine translated from a character string specifying if a
 matrix has unit diagonal or not to the relevant BLAST-specified
 integer constant.

 ILADIAG returns an INTEGER.  If ILADIAG < 0, then the input is not a
 character indicating a unit or non-unit diagonal.  Otherwise ILADIAG
 returns the constant value corresponding to DIAG.
.fi
.PP
 
.RE
.PP
\fBAuthor:\fP
.RS 4
Univ\&. of Tennessee 
.PP
Univ\&. of California Berkeley 
.PP
Univ\&. of Colorado Denver 
.PP
NAG Ltd\&. 
.RE
.PP
\fBDate:\fP
.RS 4
November 2011 
.RE
.PP

.PP
Definition at line 59 of file iladiag\&.f\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for LAPACK from the source code\&.
