.TH "ilatrans.f" 3 "Sat Nov 16 2013" "Version 3.4.2" "LAPACK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ilatrans.f \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "INTEGER function \fBilatrans\fP (TRANS)"
.br
.RI "\fI\fBILATRANS\fP \fP"
.in -1c
.SH "Function/Subroutine Documentation"
.PP 
.SS "INTEGER function ilatrans (characterTRANS)"

.PP
\fBILATRANS\fP  
.PP
\fBPurpose: \fP
.RS 4

.PP
.nf
 This subroutine translates from a character string specifying a
 transposition operation to the relevant BLAST-specified integer
 constant.

 ILATRANS returns an INTEGER.  If ILATRANS < 0, then the input is not
 a character indicating a transposition operator.  Otherwise ILATRANS
 returns the constant value corresponding to TRANS.
.fi
.PP
 
.RE
.PP
\fBAuthor:\fP
.RS 4
Univ\&. of Tennessee 
.PP
Univ\&. of California Berkeley 
.PP
Univ\&. of Colorado Denver 
.PP
NAG Ltd\&. 
.RE
.PP
\fBDate:\fP
.RS 4
November 2011 
.RE
.PP

.PP
Definition at line 59 of file ilatrans\&.f\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for LAPACK from the source code\&.
