.TH "ilauplo.f" 3 "Sat Nov 16 2013" "Version 3.4.2" "LAPACK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ilauplo.f \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "INTEGER function \fBilauplo\fP (UPLO)"
.br
.RI "\fI\fBILAUPLO\fP \fP"
.in -1c
.SH "Function/Subroutine Documentation"
.PP 
.SS "INTEGER function ilauplo (characterUPLO)"

.PP
\fBILAUPLO\fP  
.PP
\fBPurpose: \fP
.RS 4

.PP
.nf
 This subroutine translated from a character string specifying a
 upper- or lower-triangular matrix to the relevant BLAST-specified
 integer constant.

 ILAUPLO returns an INTEGER.  If ILAUPLO < 0, then the input is not
 a character indicating an upper- or lower-triangular matrix.
 Otherwise ILAUPLO returns the constant value corresponding to UPLO.
.fi
.PP
 
.RE
.PP
\fBAuthor:\fP
.RS 4
Univ\&. of Tennessee 
.PP
Univ\&. of California Berkeley 
.PP
Univ\&. of Colorado Denver 
.PP
NAG Ltd\&. 
.RE
.PP
\fBDate:\fP
.RS 4
November 2011 
.RE
.PP

.PP
Definition at line 59 of file ilauplo\&.f\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for LAPACK from the source code\&.
