.TH "ilaver.f" 3 "Sat Nov 16 2013" "Version 3.4.2" "LAPACK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ilaver.f \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "subroutine \fBilaver\fP (VERS_MAJOR, VERS_MINOR, VERS_PATCH)"
.br
.RI "\fI\fBILAVER\fP returns the LAPACK version\&. \fP"
.in -1c
.SH "Function/Subroutine Documentation"
.PP 
.SS "subroutine ilaver (integerVERS_MAJOR, integerVERS_MINOR, integerVERS_PATCH)"

.PP
\fBILAVER\fP returns the LAPACK version\&. \fBPurpose: \fP
.RS 4

.PP
.nf
  This subroutine returns the LAPACK version.
.fi
.PP
 
.RE
.PP
\fBParameters:\fP
.RS 4
\fIVERS_MAJOR\fP return the lapack major version
.br
\fIVERS_MINOR\fP return the lapack minor version from the major version
.br
\fIVERS_PATCH\fP return the lapack patch version from the minor version 
.RE
.PP
\fBAuthor:\fP
.RS 4
Univ\&. of Tennessee 
.PP
Univ\&. of California Berkeley 
.PP
Univ\&. of Colorado Denver 
.PP
NAG Ltd\&. 
.RE
.PP
\fBDate:\fP
.RS 4
November 2013 
.RE
.PP

.PP
Definition at line 49 of file INSTALL/ilaver\&.f\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for LAPACK from the source code\&.
