.TH "lsame.f" 3 "Sat Nov 16 2013" "Version 3.4.2" "LAPACK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lsame.f \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "LOGICAL function \fBlsame\fP (CA, CB)"
.br
.RI "\fI\fBLSAME\fP \fP"
.in -1c
.SH "Function/Subroutine Documentation"
.PP 
.SS "LOGICAL function lsame (characterCA, characterCB)"

.PP
\fBLSAME\fP \fBPurpose: \fP
.RS 4

.PP
.nf
 LSAME returns .TRUE. if CA is the same letter as CB regardless of
 case.
.fi
.PP
 
.RE
.PP
\fBParameters:\fP
.RS 4
\fICA\fP 
.PP
.nf
 
.fi
.PP
.br
\fICB\fP 
.PP
.nf
          CA and CB specify the single characters to be compared.
.fi
.PP
 
.RE
.PP
\fBAuthor:\fP
.RS 4
Univ\&. of Tennessee 
.PP
Univ\&. of California Berkeley 
.PP
Univ\&. of Colorado Denver 
.PP
NAG Ltd\&. 
.RE
.PP
\fBDate:\fP
.RS 4
November 2011 
.RE
.PP

.PP
Definition at line 52 of file INSTALL/lsame\&.f\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for LAPACK from the source code\&.
