.TH "izamax.f" 3 "Sat Nov 16 2013" "Version 3.4.2" "LAPACK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
izamax.f \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "INTEGER function \fBizamax\fP (N, ZX, INCX)"
.br
.RI "\fI\fBIZAMAX\fP \fP"
.in -1c
.SH "Function/Subroutine Documentation"
.PP 
.SS "INTEGER function izamax (integerN, complex*16, dimension(*)ZX, integerINCX)"

.PP
\fBIZAMAX\fP \fBPurpose: \fP
.RS 4

.PP
.nf
    IZAMAX finds the index of element having max. absolute value.
.fi
.PP
 
.RE
.PP
\fBAuthor:\fP
.RS 4
Univ\&. of Tennessee 
.PP
Univ\&. of California Berkeley 
.PP
Univ\&. of Colorado Denver 
.PP
NAG Ltd\&. 
.RE
.PP
\fBDate:\fP
.RS 4
November 2011 
.RE
.PP
\fBFurther Details: \fP
.RS 4

.PP
.nf
     jack dongarra, 1/15/85.
     modified 3/93 to return if incx .le. 0.
     modified 12/3/93, array(1) declarations changed to array(*)
.fi
.PP
 
.RE
.PP

.PP
Definition at line 52 of file izamax\&.f\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for LAPACK from the source code\&.
