.TH "izmax1.f" 3 "Sat Nov 16 2013" "Version 3.4.2" "LAPACK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
izmax1.f \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "INTEGER function \fBizmax1\fP (N, CX, INCX)"
.br
.RI "\fI\fBIZMAX1\fP finds the index of the vector element whose real part has maximum absolute value\&. \fP"
.in -1c
.SH "Function/Subroutine Documentation"
.PP 
.SS "INTEGER function izmax1 (integerN, complex*16, dimension( * )CX, integerINCX)"

.PP
\fBIZMAX1\fP finds the index of the vector element whose real part has maximum absolute value\&.  
.PP
\fBPurpose: \fP
.RS 4

.PP
.nf
 IZMAX1 finds the index of the element whose real part has maximum
 absolute value.

 Based on IZAMAX from Level 1 BLAS.
 The change is to use the 'genuine' absolute value.
.fi
.PP
 
.RE
.PP
\fBParameters:\fP
.RS 4
\fIN\fP 
.PP
.nf
          N is INTEGER
          The number of elements in the vector CX.
.fi
.PP
.br
\fICX\fP 
.PP
.nf
          CX is COMPLEX*16 array, dimension (N)
          The vector whose elements will be summed.
.fi
.PP
.br
\fIINCX\fP 
.PP
.nf
          INCX is INTEGER
          The spacing between successive values of CX.  INCX >= 1.
.fi
.PP
 
.RE
.PP
\fBAuthor:\fP
.RS 4
Univ\&. of Tennessee 
.PP
Univ\&. of California Berkeley 
.PP
Univ\&. of Colorado Denver 
.PP
NAG Ltd\&. 
.RE
.PP
\fBDate:\fP
.RS 4
September 2012 
.RE
.PP
\fBContributors: \fP
.RS 4
Nick Higham for use with ZLACON\&. 
.RE
.PP

.PP
Definition at line 82 of file izmax1\&.f\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for LAPACK from the source code\&.
