.TH "scsum1.f" 3 "Sat Nov 16 2013" "Version 3.4.2" "LAPACK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
scsum1.f \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "REAL function \fBscsum1\fP (N, CX, INCX)"
.br
.RI "\fI\fBSCSUM1\fP forms the 1-norm of the complex vector using the true absolute value\&. \fP"
.in -1c
.SH "Function/Subroutine Documentation"
.PP 
.SS "REAL function scsum1 (integerN, complex, dimension( * )CX, integerINCX)"

.PP
\fBSCSUM1\fP forms the 1-norm of the complex vector using the true absolute value\&.  
.PP
\fBPurpose: \fP
.RS 4

.PP
.nf
 SCSUM1 takes the sum of the absolute values of a complex
 vector and returns a single precision result.

 Based on SCASUM from the Level 1 BLAS.
 The change is to use the 'genuine' absolute value.
.fi
.PP
 
.RE
.PP
\fBParameters:\fP
.RS 4
\fIN\fP 
.PP
.nf
          N is INTEGER
          The number of elements in the vector CX.
.fi
.PP
.br
\fICX\fP 
.PP
.nf
          CX is COMPLEX array, dimension (N)
          The vector whose elements will be summed.
.fi
.PP
.br
\fIINCX\fP 
.PP
.nf
          INCX is INTEGER
          The spacing between successive values of CX.  INCX > 0.
.fi
.PP
 
.RE
.PP
\fBAuthor:\fP
.RS 4
Univ\&. of Tennessee 
.PP
Univ\&. of California Berkeley 
.PP
Univ\&. of Colorado Denver 
.PP
NAG Ltd\&. 
.RE
.PP
\fBDate:\fP
.RS 4
September 2012 
.RE
.PP
\fBContributors: \fP
.RS 4
Nick Higham for use with CLACON\&. 
.RE
.PP

.PP
Definition at line 82 of file scsum1\&.f\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for LAPACK from the source code\&.
