.TH "sdsdot.f" 3 "Sat Nov 16 2013" "Version 3.4.2" "LAPACK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sdsdot.f \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "REAL function \fBsdsdot\fP (N, SB, SX, INCX, SY, INCY)"
.br
.RI "\fI\fBSDSDOT\fP \fP"
.in -1c
.SH "Function/Subroutine Documentation"
.PP 
.SS "REAL function sdsdot (integerN, realSB, real, dimension(*)SX, integerINCX, real, dimension(*)SY, integerINCY)"

.PP
\fBSDSDOT\fP \fBPurpose: \fP
.RS 4

.PP
.nf
 
.fi
.PP
 
.RE
.PP
\fBAuthor:\fP
.RS 4
Univ\&. of Tennessee 
.PP
Univ\&. of California Berkeley 
.PP
Univ\&. of Colorado Denver 
.PP
NAG Ltd\&. 
.RE
.PP
\fBDate:\fP
.RS 4
November 2011 
.RE
.PP

.PP
Definition at line 141 of file sdsdot\&.f\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for LAPACK from the source code\&.
