.TH "second_EXT_ETIME_.f" 3 "Sat Nov 16 2013" "Version 3.4.2" "LAPACK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
second_EXT_ETIME_.f \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "REAL function \fBsecond\fP ()"
.br
.RI "\fI\fBSECOND\fP Using ETIME_ \fP"
.in -1c
.SH "Function/Subroutine Documentation"
.PP 
.SS "REAL function second ()"

.PP
\fBSECOND\fP Using ETIME_ \fBPurpose: \fP
.RS 4

.PP
.nf
  SECOND returns the user time for a process in seconds.
  This version gets the time from the system function ETIME_.
.fi
.PP
 
.RE
.PP
\fBAuthor:\fP
.RS 4
Univ\&. of Tennessee 
.PP
Univ\&. of California Berkeley 
.PP
Univ\&. of Colorado Denver 
.PP
NAG Ltd\&. 
.RE
.PP
\fBDate:\fP
.RS 4
November 2011 
.RE
.PP

.PP
Definition at line 36 of file second_EXT_ETIME_\&.f\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for LAPACK from the source code\&.
