.TH "slacon.f" 3 "Sat Nov 16 2013" "Version 3.4.2" "LAPACK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
slacon.f \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "subroutine \fBslacon\fP (N, V, X, ISGN, EST, KASE)"
.br
.RI "\fI\fBSLACON\fP estimates the 1-norm of a square matrix, using reverse communication for evaluating matrix-vector products\&. \fP"
.in -1c
.SH "Function/Subroutine Documentation"
.PP 
.SS "subroutine slacon (integerN, real, dimension( * )V, real, dimension( * )X, integer, dimension( * )ISGN, realEST, integerKASE)"

.PP
\fBSLACON\fP estimates the 1-norm of a square matrix, using reverse communication for evaluating matrix-vector products\&.  
.PP
\fBPurpose: \fP
.RS 4

.PP
.nf
 SLACON estimates the 1-norm of a square, real matrix A.
 Reverse communication is used for evaluating matrix-vector products.
.fi
.PP
 
.RE
.PP
\fBParameters:\fP
.RS 4
\fIN\fP 
.PP
.nf
          N is INTEGER
         The order of the matrix.  N >= 1.
.fi
.PP
.br
\fIV\fP 
.PP
.nf
          V is REAL array, dimension (N)
         On the final return, V = A*W,  where  EST = norm(V)/norm(W)
         (W is not returned).
.fi
.PP
.br
\fIX\fP 
.PP
.nf
          X is REAL array, dimension (N)
         On an intermediate return, X should be overwritten by
               A * X,   if KASE=1,
               A**T * X,  if KASE=2,
         and SLACON must be re-called with all the other parameters
         unchanged.
.fi
.PP
.br
\fIISGN\fP 
.PP
.nf
          ISGN is INTEGER array, dimension (N)
.fi
.PP
.br
\fIEST\fP 
.PP
.nf
          EST is REAL
         On entry with KASE = 1 or 2 and JUMP = 3, EST should be
         unchanged from the previous call to SLACON.
         On exit, EST is an estimate (a lower bound) for norm(A). 
.fi
.PP
.br
\fIKASE\fP 
.PP
.nf
          KASE is INTEGER
         On the initial call to SLACON, KASE should be 0.
         On an intermediate return, KASE will be 1 or 2, indicating
         whether X should be overwritten by A * X  or A**T * X.
         On the final return from SLACON, KASE will again be 0.
.fi
.PP
 
.RE
.PP
\fBAuthor:\fP
.RS 4
Univ\&. of Tennessee 
.PP
Univ\&. of California Berkeley 
.PP
Univ\&. of Colorado Denver 
.PP
NAG Ltd\&. 
.RE
.PP
\fBDate:\fP
.RS 4
September 2012 
.RE
.PP
\fBContributors: \fP
.RS 4
Nick Higham, University of Manchester\&. 
.br
 Originally named SONEST, dated March 16, 1988\&. 
.RE
.PP
\fBReferences: \fP
.RS 4
N\&.J\&. Higham, 'FORTRAN codes for estimating the one-norm of
  a real or complex matrix, with applications to condition estimation', ACM Trans\&. Math\&. Soft\&., vol\&. 14, no\&. 4, pp\&. 381-396, December 1988\&. 
.RE
.PP

.PP
Definition at line 116 of file slacon\&.f\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for LAPACK from the source code\&.
