.TH "slapll.f" 3 "Sat Nov 16 2013" "Version 3.4.2" "LAPACK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
slapll.f \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "subroutine \fBslapll\fP (N, X, INCX, Y, INCY, SSMIN)"
.br
.RI "\fI\fBSLAPLL\fP measures the linear dependence of two vectors\&. \fP"
.in -1c
.SH "Function/Subroutine Documentation"
.PP 
.SS "subroutine slapll (integerN, real, dimension( * )X, integerINCX, real, dimension( * )Y, integerINCY, realSSMIN)"

.PP
\fBSLAPLL\fP measures the linear dependence of two vectors\&.  
.PP
\fBPurpose: \fP
.RS 4

.PP
.nf
 Given two column vectors X and Y, let

                      A = ( X Y ).

 The subroutine first computes the QR factorization of A = Q*R,
 and then computes the SVD of the 2-by-2 upper triangular matrix R.
 The smaller singular value of R is returned in SSMIN, which is used
 as the measurement of the linear dependency of the vectors X and Y.
.fi
.PP
 
.RE
.PP
\fBParameters:\fP
.RS 4
\fIN\fP 
.PP
.nf
          N is INTEGER
          The length of the vectors X and Y.
.fi
.PP
.br
\fIX\fP 
.PP
.nf
          X is REAL array,
                         dimension (1+(N-1)*INCX)
          On entry, X contains the N-vector X.
          On exit, X is overwritten.
.fi
.PP
.br
\fIINCX\fP 
.PP
.nf
          INCX is INTEGER
          The increment between successive elements of X. INCX > 0.
.fi
.PP
.br
\fIY\fP 
.PP
.nf
          Y is REAL array,
                         dimension (1+(N-1)*INCY)
          On entry, Y contains the N-vector Y.
          On exit, Y is overwritten.
.fi
.PP
.br
\fIINCY\fP 
.PP
.nf
          INCY is INTEGER
          The increment between successive elements of Y. INCY > 0.
.fi
.PP
.br
\fISSMIN\fP 
.PP
.nf
          SSMIN is REAL
          The smallest singular value of the N-by-2 matrix A = ( X Y ).
.fi
.PP
 
.RE
.PP
\fBAuthor:\fP
.RS 4
Univ\&. of Tennessee 
.PP
Univ\&. of California Berkeley 
.PP
Univ\&. of Colorado Denver 
.PP
NAG Ltd\&. 
.RE
.PP
\fBDate:\fP
.RS 4
September 2012 
.RE
.PP

.PP
Definition at line 103 of file slapll\&.f\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for LAPACK from the source code\&.
