.TH "slapy2.f" 3 "Sat Nov 16 2013" "Version 3.4.2" "LAPACK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
slapy2.f \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "REAL function \fBslapy2\fP (X, Y)"
.br
.RI "\fI\fBSLAPY2\fP returns sqrt(x2+y2)\&. \fP"
.in -1c
.SH "Function/Subroutine Documentation"
.PP 
.SS "REAL function slapy2 (realX, realY)"

.PP
\fBSLAPY2\fP returns sqrt(x2+y2)\&.  
.PP
\fBPurpose: \fP
.RS 4

.PP
.nf
 SLAPY2 returns sqrt(x**2+y**2), taking care not to cause unnecessary
 overflow.
.fi
.PP
 
.RE
.PP
\fBParameters:\fP
.RS 4
\fIX\fP 
.PP
.nf
          X is REAL
.fi
.PP
.br
\fIY\fP 
.PP
.nf
          Y is REAL
          X and Y specify the values x and y.
.fi
.PP
 
.RE
.PP
\fBAuthor:\fP
.RS 4
Univ\&. of Tennessee 
.PP
Univ\&. of California Berkeley 
.PP
Univ\&. of Colorado Denver 
.PP
NAG Ltd\&. 
.RE
.PP
\fBDate:\fP
.RS 4
September 2012 
.RE
.PP

.PP
Definition at line 64 of file slapy2\&.f\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for LAPACK from the source code\&.
