.TH "slarnv.f" 3 "Sat Nov 16 2013" "Version 3.4.2" "LAPACK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
slarnv.f \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "subroutine \fBslarnv\fP (IDIST, ISEED, N, X)"
.br
.RI "\fI\fBSLARNV\fP returns a vector of random numbers from a uniform or normal distribution\&. \fP"
.in -1c
.SH "Function/Subroutine Documentation"
.PP 
.SS "subroutine slarnv (integerIDIST, integer, dimension( 4 )ISEED, integerN, real, dimension( * )X)"

.PP
\fBSLARNV\fP returns a vector of random numbers from a uniform or normal distribution\&.  
.PP
\fBPurpose: \fP
.RS 4

.PP
.nf
 SLARNV returns a vector of n random real numbers from a uniform or
 normal distribution.
.fi
.PP
 
.RE
.PP
\fBParameters:\fP
.RS 4
\fIIDIST\fP 
.PP
.nf
          IDIST is INTEGER
          Specifies the distribution of the random numbers:
          = 1:  uniform (0,1)
          = 2:  uniform (-1,1)
          = 3:  normal (0,1)
.fi
.PP
.br
\fIISEED\fP 
.PP
.nf
          ISEED is INTEGER array, dimension (4)
          On entry, the seed of the random number generator; the array
          elements must be between 0 and 4095, and ISEED(4) must be
          odd.
          On exit, the seed is updated.
.fi
.PP
.br
\fIN\fP 
.PP
.nf
          N is INTEGER
          The number of random numbers to be generated.
.fi
.PP
.br
\fIX\fP 
.PP
.nf
          X is REAL array, dimension (N)
          The generated random numbers.
.fi
.PP
 
.RE
.PP
\fBAuthor:\fP
.RS 4
Univ\&. of Tennessee 
.PP
Univ\&. of California Berkeley 
.PP
Univ\&. of Colorado Denver 
.PP
NAG Ltd\&. 
.RE
.PP
\fBDate:\fP
.RS 4
September 2012 
.RE
.PP
\fBFurther Details: \fP
.RS 4

.PP
.nf
  This routine calls the auxiliary routine SLARUV to generate random
  real numbers from a uniform (0,1) distribution, in batches of up to
  128 using vectorisable code. The Box-Muller method is used to
  transform numbers from a uniform to a normal distribution.
.fi
.PP
 
.RE
.PP

.PP
Definition at line 98 of file slarnv\&.f\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for LAPACK from the source code\&.
