.TH "slartv.f" 3 "Sat Nov 16 2013" "Version 3.4.2" "LAPACK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
slartv.f \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "subroutine \fBslartv\fP (N, X, INCX, Y, INCY, C, S, INCC)"
.br
.RI "\fI\fBSLARTV\fP applies a vector of plane rotations with real cosines and real sines to the elements of a pair of vectors\&. \fP"
.in -1c
.SH "Function/Subroutine Documentation"
.PP 
.SS "subroutine slartv (integerN, real, dimension( * )X, integerINCX, real, dimension( * )Y, integerINCY, real, dimension( * )C, real, dimension( * )S, integerINCC)"

.PP
\fBSLARTV\fP applies a vector of plane rotations with real cosines and real sines to the elements of a pair of vectors\&.  
.PP
\fBPurpose: \fP
.RS 4

.PP
.nf
 SLARTV applies a vector of real plane rotations to elements of the
 real vectors x and y. For i = 1,2,...,n

    ( x(i) ) := (  c(i)  s(i) ) ( x(i) )
    ( y(i) )    ( -s(i)  c(i) ) ( y(i) )
.fi
.PP
 
.RE
.PP
\fBParameters:\fP
.RS 4
\fIN\fP 
.PP
.nf
          N is INTEGER
          The number of plane rotations to be applied.
.fi
.PP
.br
\fIX\fP 
.PP
.nf
          X is REAL array,
                         dimension (1+(N-1)*INCX)
          The vector x.
.fi
.PP
.br
\fIINCX\fP 
.PP
.nf
          INCX is INTEGER
          The increment between elements of X. INCX > 0.
.fi
.PP
.br
\fIY\fP 
.PP
.nf
          Y is REAL array,
                         dimension (1+(N-1)*INCY)
          The vector y.
.fi
.PP
.br
\fIINCY\fP 
.PP
.nf
          INCY is INTEGER
          The increment between elements of Y. INCY > 0.
.fi
.PP
.br
\fIC\fP 
.PP
.nf
          C is REAL array, dimension (1+(N-1)*INCC)
          The cosines of the plane rotations.
.fi
.PP
.br
\fIS\fP 
.PP
.nf
          S is REAL array, dimension (1+(N-1)*INCC)
          The sines of the plane rotations.
.fi
.PP
.br
\fIINCC\fP 
.PP
.nf
          INCC is INTEGER
          The increment between elements of C and S. INCC > 0.
.fi
.PP
 
.RE
.PP
\fBAuthor:\fP
.RS 4
Univ\&. of Tennessee 
.PP
Univ\&. of California Berkeley 
.PP
Univ\&. of Colorado Denver 
.PP
NAG Ltd\&. 
.RE
.PP
\fBDate:\fP
.RS 4
September 2012 
.RE
.PP

.PP
Definition at line 109 of file slartv\&.f\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for LAPACK from the source code\&.
