.TH "slasv2.f" 3 "Sat Nov 16 2013" "Version 3.4.2" "LAPACK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
slasv2.f \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "subroutine \fBslasv2\fP (F, G, H, SSMIN, SSMAX, SNR, CSR, SNL, CSL)"
.br
.RI "\fI\fBSLASV2\fP computes the singular value decomposition of a 2-by-2 triangular matrix\&. \fP"
.in -1c
.SH "Function/Subroutine Documentation"
.PP 
.SS "subroutine slasv2 (realF, realG, realH, realSSMIN, realSSMAX, realSNR, realCSR, realSNL, realCSL)"

.PP
\fBSLASV2\fP computes the singular value decomposition of a 2-by-2 triangular matrix\&.  
.PP
\fBPurpose: \fP
.RS 4

.PP
.nf
 SLASV2 computes the singular value decomposition of a 2-by-2
 triangular matrix
    [  F   G  ]
    [  0   H  ].
 On return, abs(SSMAX) is the larger singular value, abs(SSMIN) is the
 smaller singular value, and (CSL,SNL) and (CSR,SNR) are the left and
 right singular vectors for abs(SSMAX), giving the decomposition

    [ CSL  SNL ] [  F   G  ] [ CSR -SNR ]  =  [ SSMAX   0   ]
    [-SNL  CSL ] [  0   H  ] [ SNR  CSR ]     [  0    SSMIN ].
.fi
.PP
 
.RE
.PP
\fBParameters:\fP
.RS 4
\fIF\fP 
.PP
.nf
          F is REAL
          The (1,1) element of the 2-by-2 matrix.
.fi
.PP
.br
\fIG\fP 
.PP
.nf
          G is REAL
          The (1,2) element of the 2-by-2 matrix.
.fi
.PP
.br
\fIH\fP 
.PP
.nf
          H is REAL
          The (2,2) element of the 2-by-2 matrix.
.fi
.PP
.br
\fISSMIN\fP 
.PP
.nf
          SSMIN is REAL
          abs(SSMIN) is the smaller singular value.
.fi
.PP
.br
\fISSMAX\fP 
.PP
.nf
          SSMAX is REAL
          abs(SSMAX) is the larger singular value.
.fi
.PP
.br
\fISNL\fP 
.PP
.nf
          SNL is REAL
.fi
.PP
.br
\fICSL\fP 
.PP
.nf
          CSL is REAL
          The vector (CSL, SNL) is a unit left singular vector for the
          singular value abs(SSMAX).
.fi
.PP
.br
\fISNR\fP 
.PP
.nf
          SNR is REAL
.fi
.PP
.br
\fICSR\fP 
.PP
.nf
          CSR is REAL
          The vector (CSR, SNR) is a unit right singular vector for the
          singular value abs(SSMAX).
.fi
.PP
 
.RE
.PP
\fBAuthor:\fP
.RS 4
Univ\&. of Tennessee 
.PP
Univ\&. of California Berkeley 
.PP
Univ\&. of Colorado Denver 
.PP
NAG Ltd\&. 
.RE
.PP
\fBDate:\fP
.RS 4
September 2012 
.RE
.PP
\fBFurther Details: \fP
.RS 4

.PP
.nf
  Any input parameter may be aliased with any output parameter.

  Barring over/underflow and assuming a guard digit in subtraction, all
  output quantities are correct to within a few units in the last
  place (ulps).

  In IEEE arithmetic, the code works correctly if one matrix element is
  infinite.

  Overflow will not occur unless the largest singular value itself
  overflows or is within a few ulps of overflow. (On machines with
  partial overflow, like the Cray, overflow may occur if the largest
  singular value is within a factor of 2 of overflow.)

  Underflow is harmless if underflow is gradual. Otherwise, results
  may correspond to a matrix modified by perturbations of size near
  the underflow threshold.
.fi
.PP
 
.RE
.PP

.PP
Definition at line 139 of file slasv2\&.f\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for LAPACK from the source code\&.
