.TH "zgtsv.f" 3 "Sat Nov 16 2013" "Version 3.4.2" "LAPACK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
zgtsv.f \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "subroutine \fBzgtsv\fP (N, NRHS, DL, D, DU, B, LDB, INFO)"
.br
.RI "\fI\fB ZGTSV computes the solution to system of linear equations A * X = B for GT matrices \fB \fP\fP\fP"
.in -1c
.SH "Function/Subroutine Documentation"
.PP 
.SS "subroutine zgtsv (integerN, integerNRHS, complex*16, dimension( * )DL, complex*16, dimension( * )D, complex*16, dimension( * )DU, complex*16, dimension( ldb, * )B, integerLDB, integerINFO)"

.PP
\fB ZGTSV computes the solution to system of linear equations A * X = B for GT matrices \fB \fP\fP 
.PP
\fBPurpose: \fP
.RS 4

.PP
.nf
 ZGTSV  solves the equation

    A*X = B,

 where A is an N-by-N tridiagonal matrix, by Gaussian elimination with
 partial pivoting.

 Note that the equation  A**T *X = B  may be solved by interchanging the
 order of the arguments DU and DL.
.fi
.PP
 
.RE
.PP
\fBParameters:\fP
.RS 4
\fIN\fP 
.PP
.nf
          N is INTEGER
          The order of the matrix A.  N >= 0.
.fi
.PP
.br
\fINRHS\fP 
.PP
.nf
          NRHS is INTEGER
          The number of right hand sides, i.e., the number of columns
          of the matrix B.  NRHS >= 0.
.fi
.PP
.br
\fIDL\fP 
.PP
.nf
          DL is COMPLEX*16 array, dimension (N-1)
          On entry, DL must contain the (n-1) subdiagonal elements of
          A.
          On exit, DL is overwritten by the (n-2) elements of the
          second superdiagonal of the upper triangular matrix U from
          the LU factorization of A, in DL(1), ..., DL(n-2).
.fi
.PP
.br
\fID\fP 
.PP
.nf
          D is COMPLEX*16 array, dimension (N)
          On entry, D must contain the diagonal elements of A.
          On exit, D is overwritten by the n diagonal elements of U.
.fi
.PP
.br
\fIDU\fP 
.PP
.nf
          DU is COMPLEX*16 array, dimension (N-1)
          On entry, DU must contain the (n-1) superdiagonal elements
          of A.
          On exit, DU is overwritten by the (n-1) elements of the first
          superdiagonal of U.
.fi
.PP
.br
\fIB\fP 
.PP
.nf
          B is COMPLEX*16 array, dimension (LDB,NRHS)
          On entry, the N-by-NRHS right hand side matrix B.
          On exit, if INFO = 0, the N-by-NRHS solution matrix X.
.fi
.PP
.br
\fILDB\fP 
.PP
.nf
          LDB is INTEGER
          The leading dimension of the array B.  LDB >= max(1,N).
.fi
.PP
.br
\fIINFO\fP 
.PP
.nf
          INFO is INTEGER
          = 0:  successful exit
          < 0:  if INFO = -i, the i-th argument had an illegal value
          > 0:  if INFO = i, U(i,i) is exactly zero, and the solution
                has not been computed.  The factorization has not been
                completed unless i = N.
.fi
.PP
 
.RE
.PP
\fBAuthor:\fP
.RS 4
Univ\&. of Tennessee 
.PP
Univ\&. of California Berkeley 
.PP
Univ\&. of Colorado Denver 
.PP
NAG Ltd\&. 
.RE
.PP
\fBDate:\fP
.RS 4
September 2012 
.RE
.PP

.PP
Definition at line 125 of file zgtsv\&.f\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for LAPACK from the source code\&.
