.TH "zla_wwaddw.f" 3 "Sat Nov 16 2013" "Version 3.4.2" "LAPACK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
zla_wwaddw.f \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "subroutine \fBzla_wwaddw\fP (N, X, Y, W)"
.br
.RI "\fI\fBZLA_WWADDW\fP adds a vector into a doubled-single vector\&. \fP"
.in -1c
.SH "Function/Subroutine Documentation"
.PP 
.SS "subroutine zla_wwaddw (integerN, complex*16, dimension( * )X, complex*16, dimension( * )Y, complex*16, dimension( * )W)"

.PP
\fBZLA_WWADDW\fP adds a vector into a doubled-single vector\&.  
.PP
\fBPurpose: \fP
.RS 4

.PP
.nf
    ZLA_WWADDW adds a vector W into a doubled-single vector (X, Y).

    This works for all extant IBM's hex and binary floating point
    arithmetics, but not for decimal.
.fi
.PP
 
.RE
.PP
\fBParameters:\fP
.RS 4
\fIN\fP 
.PP
.nf
          N is INTEGER
            The length of vectors X, Y, and W.
.fi
.PP
.br
\fIX\fP 
.PP
.nf
          X is COMPLEX*16 array, dimension (N)
            The first part of the doubled-single accumulation vector.
.fi
.PP
.br
\fIY\fP 
.PP
.nf
          Y is COMPLEX*16 array, dimension (N)
            The second part of the doubled-single accumulation vector.
.fi
.PP
.br
\fIW\fP 
.PP
.nf
          W is COMPLEX*16 array, dimension (N)
            The vector to be added.
.fi
.PP
 
.RE
.PP
\fBAuthor:\fP
.RS 4
Univ\&. of Tennessee 
.PP
Univ\&. of California Berkeley 
.PP
Univ\&. of Colorado Denver 
.PP
NAG Ltd\&. 
.RE
.PP
\fBDate:\fP
.RS 4
September 2012 
.RE
.PP

.PP
Definition at line 82 of file zla_wwaddw\&.f\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for LAPACK from the source code\&.
