.TH "zla_gbrpvgrw.f" 3 "Sat Nov 16 2013" "Version 3.4.2" "LAPACK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
zla_gbrpvgrw.f \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "DOUBLE PRECISION function \fBzla_gbrpvgrw\fP (N, KL, KU, NCOLS, AB, LDAB, AFB, LDAFB)"
.br
.RI "\fI\fBZLA_GBRPVGRW\fP computes the reciprocal pivot growth factor norm(A)/norm(U) for a general banded matrix\&. \fP"
.in -1c
.SH "Function/Subroutine Documentation"
.PP 
.SS "DOUBLE PRECISION function zla_gbrpvgrw (integerN, integerKL, integerKU, integerNCOLS, complex*16, dimension( ldab, * )AB, integerLDAB, complex*16, dimension( ldafb, * )AFB, integerLDAFB)"

.PP
\fBZLA_GBRPVGRW\fP computes the reciprocal pivot growth factor norm(A)/norm(U) for a general banded matrix\&.  
.PP
\fBPurpose: \fP
.RS 4

.PP
.nf
 ZLA_GBRPVGRW computes the reciprocal pivot growth factor
 norm(A)/norm(U). The "max absolute element" norm is used. If this is
 much less than 1, the stability of the LU factorization of the
 (equilibrated) matrix A could be poor. This also means that the
 solution X, estimated condition numbers, and error bounds could be
 unreliable.
.fi
.PP
 
.RE
.PP
\fBParameters:\fP
.RS 4
\fIN\fP 
.PP
.nf
          N is INTEGER
     The number of linear equations, i.e., the order of the
     matrix A.  N >= 0.
.fi
.PP
.br
\fIKL\fP 
.PP
.nf
          KL is INTEGER
     The number of subdiagonals within the band of A.  KL >= 0.
.fi
.PP
.br
\fIKU\fP 
.PP
.nf
          KU is INTEGER
     The number of superdiagonals within the band of A.  KU >= 0.
.fi
.PP
.br
\fINCOLS\fP 
.PP
.nf
          NCOLS is INTEGER
     The number of columns of the matrix A.  NCOLS >= 0.
.fi
.PP
.br
\fIAB\fP 
.PP
.nf
          AB is COMPLEX*16 array, dimension (LDAB,N)
     On entry, the matrix A in band storage, in rows 1 to KL+KU+1.
     The j-th column of A is stored in the j-th column of the
     array AB as follows:
     AB(KU+1+i-j,j) = A(i,j) for max(1,j-KU)<=i<=min(N,j+kl)
.fi
.PP
.br
\fILDAB\fP 
.PP
.nf
          LDAB is INTEGER
     The leading dimension of the array AB.  LDAB >= KL+KU+1.
.fi
.PP
.br
\fIAFB\fP 
.PP
.nf
          AFB is COMPLEX*16 array, dimension (LDAFB,N)
     Details of the LU factorization of the band matrix A, as
     computed by ZGBTRF.  U is stored as an upper triangular
     band matrix with KL+KU superdiagonals in rows 1 to KL+KU+1,
     and the multipliers used during the factorization are stored
     in rows KL+KU+2 to 2*KL+KU+1.
.fi
.PP
.br
\fILDAFB\fP 
.PP
.nf
          LDAFB is INTEGER
     The leading dimension of the array AFB.  LDAFB >= 2*KL+KU+1.
.fi
.PP
 
.RE
.PP
\fBAuthor:\fP
.RS 4
Univ\&. of Tennessee 
.PP
Univ\&. of California Berkeley 
.PP
Univ\&. of Colorado Denver 
.PP
NAG Ltd\&. 
.RE
.PP
\fBDate:\fP
.RS 4
September 2012 
.RE
.PP

.PP
Definition at line 117 of file zla_gbrpvgrw\&.f\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for LAPACK from the source code\&.
