.TH "zladiv.f" 3 "Sat Nov 16 2013" "Version 3.4.2" "LAPACK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
zladiv.f \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "COMPLEX *16 function \fBzladiv\fP (X, Y)"
.br
.RI "\fI\fBZLADIV\fP performs complex division in real arithmetic, avoiding unnecessary overflow\&. \fP"
.in -1c
.SH "Function/Subroutine Documentation"
.PP 
.SS "COMPLEX*16 function zladiv (complex*16X, complex*16Y)"

.PP
\fBZLADIV\fP performs complex division in real arithmetic, avoiding unnecessary overflow\&.  
.PP
\fBPurpose: \fP
.RS 4

.PP
.nf
 ZLADIV := X / Y, where X and Y are complex.  The computation of X / Y
 will not overflow on an intermediary step unless the results
 overflows.
.fi
.PP
 
.RE
.PP
\fBParameters:\fP
.RS 4
\fIX\fP 
.PP
.nf
          X is COMPLEX*16
.fi
.PP
.br
\fIY\fP 
.PP
.nf
          Y is COMPLEX*16
          The complex scalars X and Y.
.fi
.PP
 
.RE
.PP
\fBAuthor:\fP
.RS 4
Univ\&. of Tennessee 
.PP
Univ\&. of California Berkeley 
.PP
Univ\&. of Colorado Denver 
.PP
NAG Ltd\&. 
.RE
.PP
\fBDate:\fP
.RS 4
September 2012 
.RE
.PP

.PP
Definition at line 65 of file zladiv\&.f\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for LAPACK from the source code\&.
