.TH "zlangt.f" 3 "Sat Nov 16 2013" "Version 3.4.2" "LAPACK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
zlangt.f \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "DOUBLE PRECISION function \fBzlangt\fP (NORM, N, DL, D, DU)"
.br
.RI "\fI\fBZLANGT\fP returns the value of the 1-norm, Frobenius norm, infinity-norm, or the largest absolute value of any element of a general tridiagonal matrix\&. \fP"
.in -1c
.SH "Function/Subroutine Documentation"
.PP 
.SS "DOUBLE PRECISION function zlangt (characterNORM, integerN, complex*16, dimension( * )DL, complex*16, dimension( * )D, complex*16, dimension( * )DU)"

.PP
\fBZLANGT\fP returns the value of the 1-norm, Frobenius norm, infinity-norm, or the largest absolute value of any element of a general tridiagonal matrix\&.  
.PP
\fBPurpose: \fP
.RS 4

.PP
.nf
 ZLANGT  returns the value of the one norm,  or the Frobenius norm, or
 the  infinity norm,  or the  element of  largest absolute value  of a
 complex tridiagonal matrix A.
.fi
.PP
.RE
.PP
\fBReturns:\fP
.RS 4
ZLANGT 
.PP
.nf
    ZLANGT = ( max(abs(A(i,j))), NORM = 'M' or 'm'
             (
             ( norm1(A),         NORM = '1', 'O' or 'o'
             (
             ( normI(A),         NORM = 'I' or 'i'
             (
             ( normF(A),         NORM = 'F', 'f', 'E' or 'e'

 where  norm1  denotes the  one norm of a matrix (maximum column sum),
 normI  denotes the  infinity norm  of a matrix  (maximum row sum) and
 normF  denotes the  Frobenius norm of a matrix (square root of sum of
 squares).  Note that  max(abs(A(i,j)))  is not a consistent matrix norm.
.fi
.PP
 
.RE
.PP
\fBParameters:\fP
.RS 4
\fINORM\fP 
.PP
.nf
          NORM is CHARACTER*1
          Specifies the value to be returned in ZLANGT as described
          above.
.fi
.PP
.br
\fIN\fP 
.PP
.nf
          N is INTEGER
          The order of the matrix A.  N >= 0.  When N = 0, ZLANGT is
          set to zero.
.fi
.PP
.br
\fIDL\fP 
.PP
.nf
          DL is COMPLEX*16 array, dimension (N-1)
          The (n-1) sub-diagonal elements of A.
.fi
.PP
.br
\fID\fP 
.PP
.nf
          D is COMPLEX*16 array, dimension (N)
          The diagonal elements of A.
.fi
.PP
.br
\fIDU\fP 
.PP
.nf
          DU is COMPLEX*16 array, dimension (N-1)
          The (n-1) super-diagonal elements of A.
.fi
.PP
 
.RE
.PP
\fBAuthor:\fP
.RS 4
Univ\&. of Tennessee 
.PP
Univ\&. of California Berkeley 
.PP
Univ\&. of Colorado Denver 
.PP
NAG Ltd\&. 
.RE
.PP
\fBDate:\fP
.RS 4
September 2012 
.RE
.PP

.PP
Definition at line 107 of file zlangt\&.f\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for LAPACK from the source code\&.
