.TH "zlaqr2.f" 3 "Sat Nov 16 2013" "Version 3.4.2" "LAPACK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
zlaqr2.f \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "subroutine \fBzlaqr2\fP (WANTT, WANTZ, N, KTOP, KBOT, NW, H, LDH, ILOZ, IHIZ, Z, LDZ, NS, ND, SH, V, LDV, NH, T, LDT, NV, WV, LDWV, WORK, LWORK)"
.br
.RI "\fI\fBZLAQR2\fP performs the unitary similarity transformation of a Hessenberg matrix to detect and deflate fully converged eigenvalues from a trailing principal submatrix (aggressive early deflation)\&. \fP"
.in -1c
.SH "Function/Subroutine Documentation"
.PP 
.SS "subroutine zlaqr2 (logicalWANTT, logicalWANTZ, integerN, integerKTOP, integerKBOT, integerNW, complex*16, dimension( ldh, * )H, integerLDH, integerILOZ, integerIHIZ, complex*16, dimension( ldz, * )Z, integerLDZ, integerNS, integerND, complex*16, dimension( * )SH, complex*16, dimension( ldv, * )V, integerLDV, integerNH, complex*16, dimension( ldt, * )T, integerLDT, integerNV, complex*16, dimension( ldwv, * )WV, integerLDWV, complex*16, dimension( * )WORK, integerLWORK)"

.PP
\fBZLAQR2\fP performs the unitary similarity transformation of a Hessenberg matrix to detect and deflate fully converged eigenvalues from a trailing principal submatrix (aggressive early deflation)\&.  
.PP
\fBPurpose: \fP
.RS 4

.PP
.nf
    ZLAQR2 is identical to ZLAQR3 except that it avoids
    recursion by calling ZLAHQR instead of ZLAQR4.

    Aggressive early deflation:

    ZLAQR2 accepts as input an upper Hessenberg matrix
    H and performs an unitary similarity transformation
    designed to detect and deflate fully converged eigenvalues from
    a trailing principal submatrix.  On output H has been over-
    written by a new Hessenberg matrix that is a perturbation of
    an unitary similarity transformation of H.  It is to be
    hoped that the final version of H has many zero subdiagonal
    entries.
.fi
.PP
 
.RE
.PP
\fBParameters:\fP
.RS 4
\fIWANTT\fP 
.PP
.nf
          WANTT is LOGICAL
          If .TRUE., then the Hessenberg matrix H is fully updated
          so that the triangular Schur factor may be
          computed (in cooperation with the calling subroutine).
          If .FALSE., then only enough of H is updated to preserve
          the eigenvalues.
.fi
.PP
.br
\fIWANTZ\fP 
.PP
.nf
          WANTZ is LOGICAL
          If .TRUE., then the unitary matrix Z is updated so
          so that the unitary Schur factor may be computed
          (in cooperation with the calling subroutine).
          If .FALSE., then Z is not referenced.
.fi
.PP
.br
\fIN\fP 
.PP
.nf
          N is INTEGER
          The order of the matrix H and (if WANTZ is .TRUE.) the
          order of the unitary matrix Z.
.fi
.PP
.br
\fIKTOP\fP 
.PP
.nf
          KTOP is INTEGER
          It is assumed that either KTOP = 1 or H(KTOP,KTOP-1)=0.
          KBOT and KTOP together determine an isolated block
          along the diagonal of the Hessenberg matrix.
.fi
.PP
.br
\fIKBOT\fP 
.PP
.nf
          KBOT is INTEGER
          It is assumed without a check that either
          KBOT = N or H(KBOT+1,KBOT)=0.  KBOT and KTOP together
          determine an isolated block along the diagonal of the
          Hessenberg matrix.
.fi
.PP
.br
\fINW\fP 
.PP
.nf
          NW is INTEGER
          Deflation window size.  1 .LE. NW .LE. (KBOT-KTOP+1).
.fi
.PP
.br
\fIH\fP 
.PP
.nf
          H is COMPLEX*16 array, dimension (LDH,N)
          On input the initial N-by-N section of H stores the
          Hessenberg matrix undergoing aggressive early deflation.
          On output H has been transformed by a unitary
          similarity transformation, perturbed, and the returned
          to Hessenberg form that (it is to be hoped) has some
          zero subdiagonal entries.
.fi
.PP
.br
\fILDH\fP 
.PP
.nf
          LDH is integer
          Leading dimension of H just as declared in the calling
          subroutine.  N .LE. LDH
.fi
.PP
.br
\fIILOZ\fP 
.PP
.nf
          ILOZ is INTEGER
.fi
.PP
.br
\fIIHIZ\fP 
.PP
.nf
          IHIZ is INTEGER
          Specify the rows of Z to which transformations must be
          applied if WANTZ is .TRUE.. 1 .LE. ILOZ .LE. IHIZ .LE. N.
.fi
.PP
.br
\fIZ\fP 
.PP
.nf
          Z is COMPLEX*16 array, dimension (LDZ,N)
          IF WANTZ is .TRUE., then on output, the unitary
          similarity transformation mentioned above has been
          accumulated into Z(ILOZ:IHIZ,ILO:IHI) from the right.
          If WANTZ is .FALSE., then Z is unreferenced.
.fi
.PP
.br
\fILDZ\fP 
.PP
.nf
          LDZ is integer
          The leading dimension of Z just as declared in the
          calling subroutine.  1 .LE. LDZ.
.fi
.PP
.br
\fINS\fP 
.PP
.nf
          NS is integer
          The number of unconverged (ie approximate) eigenvalues
          returned in SR and SI that may be used as shifts by the
          calling subroutine.
.fi
.PP
.br
\fIND\fP 
.PP
.nf
          ND is integer
          The number of converged eigenvalues uncovered by this
          subroutine.
.fi
.PP
.br
\fISH\fP 
.PP
.nf
          SH is COMPLEX*16 array, dimension KBOT
          On output, approximate eigenvalues that may
          be used for shifts are stored in SH(KBOT-ND-NS+1)
          through SR(KBOT-ND).  Converged eigenvalues are
          stored in SH(KBOT-ND+1) through SH(KBOT).
.fi
.PP
.br
\fIV\fP 
.PP
.nf
          V is COMPLEX*16 array, dimension (LDV,NW)
          An NW-by-NW work array.
.fi
.PP
.br
\fILDV\fP 
.PP
.nf
          LDV is integer scalar
          The leading dimension of V just as declared in the
          calling subroutine.  NW .LE. LDV
.fi
.PP
.br
\fINH\fP 
.PP
.nf
          NH is integer scalar
          The number of columns of T.  NH.GE.NW.
.fi
.PP
.br
\fIT\fP 
.PP
.nf
          T is COMPLEX*16 array, dimension (LDT,NW)
.fi
.PP
.br
\fILDT\fP 
.PP
.nf
          LDT is integer
          The leading dimension of T just as declared in the
          calling subroutine.  NW .LE. LDT
.fi
.PP
.br
\fINV\fP 
.PP
.nf
          NV is integer
          The number of rows of work array WV available for
          workspace.  NV.GE.NW.
.fi
.PP
.br
\fIWV\fP 
.PP
.nf
          WV is COMPLEX*16 array, dimension (LDWV,NW)
.fi
.PP
.br
\fILDWV\fP 
.PP
.nf
          LDWV is integer
          The leading dimension of W just as declared in the
          calling subroutine.  NW .LE. LDV
.fi
.PP
.br
\fIWORK\fP 
.PP
.nf
          WORK is COMPLEX*16 array, dimension LWORK.
          On exit, WORK(1) is set to an estimate of the optimal value
          of LWORK for the given values of N, NW, KTOP and KBOT.
.fi
.PP
.br
\fILWORK\fP 
.PP
.nf
          LWORK is integer
          The dimension of the work array WORK.  LWORK = 2*NW
          suffices, but greater efficiency may result from larger
          values of LWORK.

          If LWORK = -1, then a workspace query is assumed; ZLAQR2
          only estimates the optimal workspace size for the given
          values of N, NW, KTOP and KBOT.  The estimate is returned
          in WORK(1).  No error message related to LWORK is issued
          by XERBLA.  Neither H nor Z are accessed.
.fi
.PP
 
.RE
.PP
\fBAuthor:\fP
.RS 4
Univ\&. of Tennessee 
.PP
Univ\&. of California Berkeley 
.PP
Univ\&. of Colorado Denver 
.PP
NAG Ltd\&. 
.RE
.PP
\fBDate:\fP
.RS 4
September 2012 
.RE
.PP
\fBContributors: \fP
.RS 4
Karen Braman and Ralph Byers, Department of Mathematics, University of Kansas, USA 
.RE
.PP

.PP
Definition at line 269 of file zlaqr2\&.f\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for LAPACK from the source code\&.
