.TH "zlascl2.f" 3 "Sat Nov 16 2013" "Version 3.4.2" "LAPACK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
zlascl2.f \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "subroutine \fBzlascl2\fP (M, N, D, X, LDX)"
.br
.RI "\fI\fBZLASCL2\fP performs diagonal scaling on a vector\&. \fP"
.in -1c
.SH "Function/Subroutine Documentation"
.PP 
.SS "subroutine zlascl2 (integerM, integerN, double precision, dimension( * )D, complex*16, dimension( ldx, * )X, integerLDX)"

.PP
\fBZLASCL2\fP performs diagonal scaling on a vector\&.  
.PP
\fBPurpose: \fP
.RS 4

.PP
.nf
 ZLASCL2 performs a diagonal scaling on a vector:
   x <-- D * x
 where the DOUBLE PRECISION diagonal matrix D is stored as a vector.

 Eventually to be replaced by BLAS_zge_diag_scale in the new BLAS
 standard.
.fi
.PP
 
.RE
.PP
\fBParameters:\fP
.RS 4
\fIM\fP 
.PP
.nf
          M is INTEGER
     The number of rows of D and X. M >= 0.
.fi
.PP
.br
\fIN\fP 
.PP
.nf
          N is INTEGER
     The number of columns of D and X. N >= 0.
.fi
.PP
.br
\fID\fP 
.PP
.nf
          D is DOUBLE PRECISION array, length M
     Diagonal matrix D, stored as a vector of length M.
.fi
.PP
.br
\fIX\fP 
.PP
.nf
          X is COMPLEX*16 array, dimension (LDX,N)
     On entry, the vector X to be scaled by D.
     On exit, the scaled vector.
.fi
.PP
.br
\fILDX\fP 
.PP
.nf
          LDX is INTEGER
     The leading dimension of the vector X. LDX >= 0.
.fi
.PP
 
.RE
.PP
\fBAuthor:\fP
.RS 4
Univ\&. of Tennessee 
.PP
Univ\&. of California Berkeley 
.PP
Univ\&. of Colorado Denver 
.PP
NAG Ltd\&. 
.RE
.PP
\fBDate:\fP
.RS 4
September 2012 
.RE
.PP

.PP
Definition at line 92 of file zlascl2\&.f\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for LAPACK from the source code\&.
