.TH "zlaset.f" 3 "Sat Nov 16 2013" "Version 3.4.2" "LAPACK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
zlaset.f \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "subroutine \fBzlaset\fP (UPLO, M, N, ALPHA, BETA, A, LDA)"
.br
.RI "\fI\fBZLASET\fP initializes the off-diagonal elements and the diagonal elements of a matrix to given values\&. \fP"
.in -1c
.SH "Function/Subroutine Documentation"
.PP 
.SS "subroutine zlaset (characterUPLO, integerM, integerN, complex*16ALPHA, complex*16BETA, complex*16, dimension( lda, * )A, integerLDA)"

.PP
\fBZLASET\fP initializes the off-diagonal elements and the diagonal elements of a matrix to given values\&.  
.PP
\fBPurpose: \fP
.RS 4

.PP
.nf
 ZLASET initializes a 2-D array A to BETA on the diagonal and
 ALPHA on the offdiagonals.
.fi
.PP
 
.RE
.PP
\fBParameters:\fP
.RS 4
\fIUPLO\fP 
.PP
.nf
          UPLO is CHARACTER*1
          Specifies the part of the matrix A to be set.
          = 'U':      Upper triangular part is set. The lower triangle
                      is unchanged.
          = 'L':      Lower triangular part is set. The upper triangle
                      is unchanged.
          Otherwise:  All of the matrix A is set.
.fi
.PP
.br
\fIM\fP 
.PP
.nf
          M is INTEGER
          On entry, M specifies the number of rows of A.
.fi
.PP
.br
\fIN\fP 
.PP
.nf
          N is INTEGER
          On entry, N specifies the number of columns of A.
.fi
.PP
.br
\fIALPHA\fP 
.PP
.nf
          ALPHA is COMPLEX*16
          All the offdiagonal array elements are set to ALPHA.
.fi
.PP
.br
\fIBETA\fP 
.PP
.nf
          BETA is COMPLEX*16
          All the diagonal array elements are set to BETA.
.fi
.PP
.br
\fIA\fP 
.PP
.nf
          A is COMPLEX*16 array, dimension (LDA,N)
          On entry, the m by n matrix A.
          On exit, A(i,j) = ALPHA, 1 <= i <= m, 1 <= j <= n, i.ne.j;
                   A(i,i) = BETA , 1 <= i <= min(m,n)
.fi
.PP
.br
\fILDA\fP 
.PP
.nf
          LDA is INTEGER
          The leading dimension of the array A.  LDA >= max(1,M).
.fi
.PP
 
.RE
.PP
\fBAuthor:\fP
.RS 4
Univ\&. of Tennessee 
.PP
Univ\&. of California Berkeley 
.PP
Univ\&. of Colorado Denver 
.PP
NAG Ltd\&. 
.RE
.PP
\fBDate:\fP
.RS 4
September 2012 
.RE
.PP

.PP
Definition at line 107 of file zlaset\&.f\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for LAPACK from the source code\&.
