.TH "zswap.f" 3 "Sat Nov 16 2013" "Version 3.4.2" "LAPACK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
zswap.f \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "subroutine \fBzswap\fP (N, ZX, INCX, ZY, INCY)"
.br
.RI "\fI\fBZSWAP\fP \fP"
.in -1c
.SH "Function/Subroutine Documentation"
.PP 
.SS "subroutine zswap (integerN, complex*16, dimension(*)ZX, integerINCX, complex*16, dimension(*)ZY, integerINCY)"

.PP
\fBZSWAP\fP \fBPurpose: \fP
.RS 4

.PP
.nf
    ZSWAP interchanges two vectors.
.fi
.PP
 
.RE
.PP
\fBAuthor:\fP
.RS 4
Univ\&. of Tennessee 
.PP
Univ\&. of California Berkeley 
.PP
Univ\&. of Colorado Denver 
.PP
NAG Ltd\&. 
.RE
.PP
\fBDate:\fP
.RS 4
November 2011 
.RE
.PP
\fBFurther Details: \fP
.RS 4

.PP
.nf
     jack dongarra, 3/11/78.
     modified 12/3/93, array(1) declarations changed to array(*)
.fi
.PP
 
.RE
.PP

.PP
Definition at line 51 of file zswap\&.f\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for LAPACK from the source code\&.
